"use client";

// One-click PDF export of the execution plan (work items). Always available in the
// push dialog so the user can take the plan away even when no tool is connected.

import { Document, Page, Text, View, StyleSheet, pdf } from "@react-pdf/renderer";
import type { Task } from "@/lib/types";

const DISC_ORDER = ["product", "engineering", "design", "qa", "customer-success", "sales"];
const DISC_LABEL: Record<string, string> = {
  product: "Product", engineering: "Engineering", design: "Design",
  qa: "QA", "customer-success": "Customer Success", sales: "Sales",
};

const styles = StyleSheet.create({
  page: { padding: 48, fontSize: 11, fontFamily: "Helvetica", color: "#1a1a1a", lineHeight: 1.5 },
  title: { fontSize: 20, fontFamily: "Helvetica-Bold", marginBottom: 4 },
  meta: { fontSize: 9, color: "#888888", marginBottom: 18 },
  group: { fontSize: 12, fontFamily: "Helvetica-Bold", marginTop: 14, marginBottom: 6, color: "#111111" },
  item: { marginBottom: 8, paddingBottom: 6, borderBottomWidth: 1, borderBottomColor: "#eeeeee" },
  itemTitle: { fontSize: 11, fontFamily: "Helvetica-Bold" },
  itemMeta: { fontSize: 9, color: "#666666", marginTop: 1 },
  detail: { fontSize: 9, color: "#555555", marginTop: 2 },
});

function PlanDocument({ tasks, projectName }: { tasks: Task[]; projectName: string }) {
  const known = DISC_ORDER.filter((d) => tasks.some((t) => t.discipline === d));
  const extras = [...new Set(tasks.map((t) => t.discipline))].filter((d) => !DISC_ORDER.includes(d));
  return (
    <Document title={`${projectName} — Execution plan`}>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>{projectName}</Text>
        <Text style={styles.meta}>Execution plan · {tasks.length} work items · Generated by Orbit · {new Date().toLocaleDateString()}</Text>
        {[...known, ...extras].map((disc) => (
          <View key={disc}>
            <Text style={styles.group}>{DISC_LABEL[disc] ?? disc}</Text>
            {tasks.filter((t) => t.discipline === disc).map((t) => (
              <View key={t.id} style={styles.item}>
                <Text style={styles.itemTitle}>{t.title}</Text>
                <Text style={styles.itemMeta}>
                  {t.priority}
                  {typeof t.estimate === "number" ? ` · ${t.estimate} pts` : ""}
                  {t.assignee?.name ? ` · ${t.assignee.name}` : ""}
                </Text>
                {t.description ? <Text style={styles.detail}>{t.description}</Text> : null}
                {t.links?.reason ? <Text style={styles.detail}>Why: {t.links.reason}</Text> : null}
              </View>
            ))}
          </View>
        ))}
      </Page>
    </Document>
  );
}

export async function downloadPlanPdf(tasks: Task[], projectName: string) {
  const blob = await pdf(<PlanDocument tasks={tasks} projectName={projectName} />).toBlob();
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${projectName.replace(/[^\w.-]+/g, "-").slice(0, 60)}-execution-plan.pdf`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
