"use client";

// One-click PDF export of a PRD (fully client-side, no backend needed). This is
// the always-available fallback in the Review Screen's Publish menu — used when
// no doc tool is connected, or whenever the user just wants a file to share.

import { Document, Page, Text, View, StyleSheet, pdf } from "@react-pdf/renderer";
import type { ProjectPRD } from "@/lib/types";

const styles = StyleSheet.create({
  page: { padding: 48, fontSize: 11, fontFamily: "Helvetica", color: "#1a1a1a", lineHeight: 1.5 },
  title: { fontSize: 20, fontFamily: "Helvetica-Bold", marginBottom: 6 },
  meta: { fontSize: 9, color: "#888888", marginBottom: 18 },
  h2: { fontSize: 12, fontFamily: "Helvetica-Bold", marginTop: 16, marginBottom: 6, color: "#111111" },
  para: { marginBottom: 4 },
  li: { flexDirection: "row", marginBottom: 3 },
  bullet: { width: 12 },
  liText: { flex: 1 },
  metricRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 3, borderBottomWidth: 1, borderBottomColor: "#eeeeee", paddingBottom: 2 },
});

function Section({ heading, children }: { heading: string; children: React.ReactNode }) {
  return (
    <View>
      <Text style={styles.h2}>{heading}</Text>
      {children}
    </View>
  );
}

function Bullets({ items }: { items: string[] }) {
  return (
    <>
      {items.map((t, i) => (
        <View style={styles.li} key={i}>
          <Text style={styles.bullet}>•</Text>
          <Text style={styles.liText}>{t}</Text>
        </View>
      ))}
    </>
  );
}

export function PrdDocument({ prd, projectName }: { prd: ProjectPRD; projectName: string }) {
  return (
    <Document title={prd.title || projectName}>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>{prd.title || projectName}</Text>
        <Text style={styles.meta}>Product Requirements · Generated by Orbit · {new Date().toLocaleDateString()}</Text>

        {prd.problem ? <Section heading="Problem"><Text style={styles.para}>{prd.problem}</Text></Section> : null}
        {prd.background ? <Section heading="Background"><Text style={styles.para}>{prd.background}</Text></Section> : null}
        {prd.goals?.length ? <Section heading="Goals"><Bullets items={prd.goals} /></Section> : null}
        {prd.nonGoals?.length ? <Section heading="Non-goals"><Bullets items={prd.nonGoals} /></Section> : null}
        {prd.functionalRequirements?.length ? <Section heading="Functional requirements"><Bullets items={prd.functionalRequirements} /></Section> : null}
        {prd.acceptanceCriteria?.length ? <Section heading="Acceptance criteria"><Bullets items={prd.acceptanceCriteria} /></Section> : null}
        {prd.dependencies?.length ? <Section heading="Dependencies"><Bullets items={prd.dependencies} /></Section> : null}
        {prd.risks?.length ? <Section heading="Risks"><Bullets items={prd.risks} /></Section> : null}
        {prd.successMetrics?.length ? (
          <Section heading="Success metrics">
            {prd.successMetrics.map((m, i) => (
              <View style={styles.metricRow} key={i}>
                <Text>{m.metric}</Text>
                <Text>{m.target}</Text>
              </View>
            ))}
          </Section>
        ) : null}
        {prd.userStories?.length ? (
          <Section heading="User stories">
            {prd.userStories.map((s) => (
              <View style={styles.li} key={s.id}>
                <Text style={styles.liText}>[{s.priority}] {s.persona}: {s.story}</Text>
              </View>
            ))}
          </Section>
        ) : null}
      </Page>
    </Document>
  );
}

export async function downloadPrdPdf(prd: ProjectPRD, projectName: string) {
  const blob = await pdf(<PrdDocument prd={prd} projectName={projectName} />).toBlob();
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${(prd.title || projectName).replace(/[^\w.-]+/g, "-").slice(0, 60)}-PRD.pdf`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
